### ISSUE TITLE
Segfault running in X

### ISSUE THREAD

**Issue by smlx** [emersion/mako#32]
Running mako in a terminal in regular X11/i3 causes a segfault. Not a big deal functionally, but might be nice to handle this cleanly.

```
$ git describe --long --all
heads/master-0-gf66545
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6efc033 in wl_proxy_marshal_constructor (proxy=0x0, opcode=1, interface=0x555555761c80 <wl_registry_interface>) at src/wayland-client.c:824
824	src/wayland-client.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff6efc033 in wl_proxy_marshal_constructor (proxy=0x0, opcode=1, interface=0x555555761c80 <wl_registry_interface>) at src/wayland-client.c:824
        args = {{i = 2, u = 2, f = 2, s = 0x2 <error: Cannot access memory at address 0x2>, o = 0x2, n = 2, a = 0x2, h = 2}, {i = 0, u = 0, f = 0, s = 0x0, o = 0x0, n = 0, a = 0x0, h = 0} <repeats 19 times>}
        ap = {{gp_offset = 0, fp_offset = 0, overflow_arg_area = 0x0, reg_save_area = 0x0}}
#1  0x000055555555cbf2 in wl_display_get_registry (wl_display=0x0) at /usr/local/include/wayland-client-protocol.h:978
        registry = 0x7fffffffe180
#2  0x000055555555db3e in init_wayland (state=0x7fffffffdeb0) at ../wayland.c:263
No locals.
#3  0x000055555555b0bc in init (state=0x7fffffffdeb0) at ../main.c:41
No locals.
#4  0x000055555555b288 in main (argc=1, argv=0x7fffffffe188) at ../main.c:83
        state = {config = {font = 0x555555770ec0 "monospace 10", width = 300, height = 100, padding = 5, border_size = 1, markup = true, format = 0x555555770ee0 "<b>%s</b>\n%b", actions = true, margin = {top = 10, right = 10, 
              bottom = 10, left = 10}, max_visible = 5, output = 0x555555770f00 "", default_timeout = 0, colors = {background = 676689919, text = 4294967295, border = 1282972159}, button_bindings = {
              left = MAKO_BUTTON_BINDING_INVOKE_DEFAULT_ACTION, right = MAKO_BUTTON_BINDING_DISMISS, middle = MAKO_BUTTON_BINDING_NONE}}, event_loop = {fds = {{fd = 0, events = 0, revents = 0}, {fd = 0, events = 0, 
                revents = 0}, {fd = 0, events = 0, revents = 0}}, bus = 0x0, display = 0x0, running = false, timers = {prev = 0x0, next = 0x0}, next_timer = 0x0}, bus = 0x555555771130, xdg_slot = 0x5555557741b0, 
          mako_slot = 0x5555557740d0, display = 0x0, registry = 0x0, compositor = 0x0, shm = 0x0, layer_shell = 0x0, xdg_output_manager = 0x0, pointers = {prev = 0x7fffffffdfa8, next = 0x7fffffffdfa8}, outputs = {
            prev = 0x7fffffffdfb8, next = 0x7fffffffdfb8}, surface = 0x0, surface_output = 0x0, layer_surface = 0x0, layer_surface_output = 0x0, configured = false, scale = 0, width = 0, height = 0, buffers = {{buffer = 0x0, 
              surface = 0x0, cairo = 0x0, pango = 0x0, width = 0, height = 0, data = 0x0, size = 0, busy = false}, {buffer = 0x0, surface = 0x0, cairo = 0x0, pango = 0x0, width = 0, height = 0, data = 0x0, size = 0, 
              busy = false}}, current_buffer = 0x0, last_id = 0, notifications = {prev = 0x0, next = 0x0}}
        ret = 0
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 18374686479671623680, 71776123339472640, 18446744073709551360, 18446744073709551615, 18374686479671623680, 71776123339472640, 
              0, 0, 93824994427904, 93824994427152, 0, 0, 0, 0, 0}}, sa_flags = 0, sa_restorer = 0x0}
```

**Comment by emersion** [comment]
Yeah, you're right. Would you mind submitting a PR to check for NULL? Thanks!
